on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v0.*' # Push events to matching v*, i.e. v1.0, v20.15.10
name: Create Pre Release
jobs:
  build:
    name: Create Pre Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_pre_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          # This can be dynamically created used body_path and a path to a .md file
          body: |
            ## Changes in this Release
            _Pre Release Changes_
            - First Change 
            - Second Change 
          draft: false
          prerelease: true